% Wiezy = struct('typ',{},... % dopisanych czy kinematyczny
%     'klasa',{},... % para postepowa czy obrotowa (innych na razie nie ma)
%     'bodyi',{},... % numer pierwszego ciala
%     'bodyj',{},... % numer drugiego ciala
%     'sA',{},... % wektor sA w i-tym ukladzie
%     'sB',{},... % wektor sB w j-tym ukladzie
%     'phi0',{},... % kat phi0 (jezeli para obrotowa - nie uzywamy)
%     'perp',{},... % wersor prostopadly osi ruch (jezeli para obrotowa - nie uzywamy)
%     'fodt',{},... % funkcja od czasu dla wiezow dopisanych
%     'dotfodt',{},... % pochodna funkcji od czasu dla wiezow dopisanych
%     'ddotfodt',{}) % druga pochodna funkcji od czasu dla wiezow dopisanych

a = 1;
b = 5;
c = 4;

Wiezy(1) = cell2struct(...
    {'kinematyczny', 'obrotowy', 0, 1,  [0;0], [0;0], [], [], [], [], []}', ...
    fieldnames(Wiezy));
Wiezy(2) = cell2struct(...
    {'kinematyczny', 'obrotowy', 1, 2,  [a;0], [0;0], [], [], [], [], []}', ...
    fieldnames(Wiezy));
Wiezy(3) = cell2struct(...
    {'kinematyczny', 'obrotowy', 2, 3,  [b;0], [0;0], [], [], [], [], []}', ...
    fieldnames(Wiezy));
Wiezy(4) = cell2struct(...
    {'kinematyczny', 'postepowy', 3, 0,  [0;0], [-b;c], 0, [0;1], [], [], []}', ...
    fieldnames(Wiezy));

Wiezy(5) = cell2struct(...
    {'dopisany', 'obrotowy', 1, 0,  [], [], [], [], 't*t+pi/2', '2*t', '2'}', ...
   fieldnames(Wiezy));